### ISSUE TITLE
Upduino ICE40UP5k ICEPROG doesnt  work.

### ISSUE THREAD

**Issue by j0t4** [cliffordwolf/icestorm#111]
I tried with rgb example here ...
https://github.com/cliffordwolf/icestorm/tree/master/examples/up5k_rgb

I used the same connections as a working setup with Lattice Diamond programmer, FTDI2232H (channel A). 

I get no errors on "sudo make prog" after successful "make",  but fpga  don't get  programmed.
I can see ft2232 pins "talk" to fpga board when i type "sudo make prog" with a logic analyzer but  I have no experience with SPI or  jtag to go further.
 
Someone has a working setup with RGB example trough "Makefile" and "make prog" con FTDI2232?
THanks

**Comment by daveshah1** [comment]
I suspect the problem is that the example "make prog" is set up to program SRAM, not flash. Either remove the flash CS jumper and swap MISO and MOSI to program SRAM, or change the target Makefile from
```
$(ICEPROG) -S $<
```
to
```
$(ICEPROG) $<
```

**Comment by j0t4** [comment]
Thanks !  
Working like a charm!

**Comment by mkvenkit** [comment]
@daveshah1  Thanks for this - just saved me some time!
