### ISSUE TITLE
Breaking icestick with icestorm ?

### ISSUE THREAD

**Issue by Martoni** [cliffordwolf/icestorm#15]
On the icestorm official web page : 
http://www.clifford.at/icestorm/

It's written that we can break our icestick with this project. Have you ever break an icestick or it's just a warning ?

Thanks

**Comment by cliffordwolf** [comment]
Its just a warning. I have never broken one and so far I have not heard from anyone who broke one. There is one anecdote, but it seems like it that case the serial flash on the icestick just died because it exceeded its number of write cycles.
