### ISSUE TITLE
Unable to resolve delay for path ce -> ltout in cell type LogicCell40!

### ISSUE THREAD

**Issue by sensille** [cliffordwolf/icestorm#185]
The command "icetime -tmd hx8k v5.asc" produces the error mentioned in the title. v5.asc can be found here: http://djfk.net/3dpfs/v5.asc

What other information do you need?

**Comment by daveshah1** [comment]
I am unable to reproduce this on the latest git head. Are you sure your icestorm install is up to date?

**Comment by sensille** [comment]
no, I used the version coming with the OS. Will build from source, sorry.

**Comment by sensille** [comment]
Using the latest HEAD helped, thanks.
