### ISSUE TITLE
Trying to build on macOS, I got this error.

### ISSUE THREAD

**Issue by enKoding** [cliffordwolf/icestorm#195]
**iceprog.c:28:10: fatal error: 'ftdi.h' file not found**

**Comment by daveshah1** [comment]
Did you follow the Mac OS X instructions at http://www.clifford.at/icestorm/notes_osx.html? If not, what did you use to install libftdi?

**Comment by enKoding** [comment]
Sorry, didn't see that. Thank you.

**Comment by dcmcshan** [comment]
https://www.clifford.at/icestorm/notes_osx.html just redirects to https://clifford.at.  Can you direct me to correct location for OSX install?
