### ISSUE TITLE
Error: Got .io_tile statement for logic tile

### ISSUE THREAD

**Issue by zzdts** [cliffordwolf/icestorm#258]
At the end of make , icepack errors happen:
```
icepack top.asc top.bin
Error: Got .io_tile statement for logic tile 1 -1855121696.
```

platform: macos Catalina 10.15.5

**Comment by daveshah1** [comment]
This looks similar to #231, but I don't know if the root cause was ever identified - do you remember if you fixed it @xobs ?

**Comment by xobs** [comment]
Never did figure out the root cause of it. Those packages were attempts to build this project under Windows and not cross-compiled so we could build it under Conda, but there were other issues with that build system so I abandoned the attempt and never looked into what caused that problem.

**Comment by zzdts** [comment]
Asc file  line ending with unix type.   
I cp top.asc to ubuntu and run "icepack top.asc top.bin" ,it works well.

**Comment by zzdts** [comment]
I fond this project and the build system support macos  [https://github.com/FPGAwars/toolchain-icestorm](https://github.com/FPGAwars/toolchain-icestorm)
It's works well on Mac.
@xobs  @daveshah1

**Comment by xobs** [comment]
We've taken that and adapted it to work with more tools, including nextpnr. The resulting toolchains are built daily and are available at https://github.com/open-tool-forge/fpga-toolchain
