### ISSUE TITLE
Problem building on Mac OS X 10.9.5

### ISSUE THREAD

**Issue by gc179** [cliffordwolf/icestorm#29]
Hello,

The make fails with:

[Geoffreys-MacBook-Pro-2:fpga/tools/icestorm] geoffc% make
/Applications/Xcode.app/Contents/Developer/usr/bin/make -C icebox
make[1]: Nothing to be done for `all'.
/Applications/Xcode.app/Contents/Developer/usr/bin/make -C icepack
make[1]: Nothing to be done for `all'.
/Applications/Xcode.app/Contents/Developer/usr/bin/make -C iceprog
clang -MD -O0 -ggdb -Wall -std=c99 -I/usr/local/include   -c -o iceprog.o iceprog.c
In file included from iceprog.c:27:
/usr/local/include/ftdi.h:20:10: fatal error: 'usb.h' file not found
#include <usb.h>
         ^
1 error generated.
make[1]: *** [iceprog.o] Error 1
make: *** [all] Error 2

I'm not sure which package I might need to supply the usb.h file. Has anyone else run across this one?

Thanks.

Geoff

**Comment by jacobrosenthal** [comment]
makes for me on osx. Presumably you're missing libusb or libusb-compat (I dont know which as I have both installed)

Grab them with homebrew
`brew install libusb libusb-compat`

**Comment by gc179** [comment]
Thanks! It turned out I had libusb and libusb-compat but libusb-compat was Somehow Messed Up (tm).

A brew uninstall/install got it to build, and I got the whole toolchain built and made the 'rot' example.

Now if Newark would just ship my iCEstick! :)

Geoff

**Comment by silardg** [comment]
I would reopen this as it is still giving this error. 
<img width="981" alt="Screenshot 2023-07-03 at 13 28 57" src="https://github.com/YosysHQ/icestorm/assets/10872257/92571599-c9c6-4a7c-a180-63fac79de240">
