### ISSUE TITLE
icetime runs make_lc40 on IO tile

### ISSUE THREAD

**Issue by zeldin** [cliffordwolf/icestorm#32]
Hi.  I found a strange thing running icetime.

If a logic tile with Y=1 has C_ON set for LC_0 (which my design has for some reason, don't know if this is normal), icetime will call make_lc40() with Y=0.  But Y=0 is not a logic tile, it's an IO tile.  So trying to interpret the config bits as a logic tile will probably produce garbage.  Under some circumstances it even proceeds to Y=-1 and crashes.

As I said, no idea if C_ON for a logic cell in this position is normal, but the design was generated with yosys 0.6 and latest arachne-pnr, and does not contain any hand-rolled logic cells...

**Comment by cliffordwolf** [comment]
Oops. Thanks for looking into that. I've now fixed it.
