### ISSUE TITLE
Timing estimate: 0.00 ns (inf MHz)

### ISSUE THREAD

**Issue by whitequark** [cliffordwolf/icestorm#45]
Using attached bitstream, `fpga-icestorm 0~20160218gitf2b2549-` from Debian and running `icetime -d hx8k -p board/iCE40HX8K-B-EVM.pcf -P ct256 test.txt`.
[test.txt](https://github.com/cliffordwolf/icestorm/files/313114/test.txt)

**Comment by cliffordwolf** [comment]
This design is empty. It contains no paths. I'm not sure what result from icetime you have expected in this case.. I've now improved the error message printed in such a case in commit 6a0fabc.

**Comment by whitequark** [comment]
@cliffordwolf Yeah, just the error message was confusing. I should've mentioned that, sorry.
