### ISSUE TITLE
.pcf parser doesn't accept some comments

### ISSUE THREAD

**Issue by whitequark** [cliffordwolf/icestorm#46]
This is fine:
```
# D9
set_io led[0]     B5
```
This breaks (but is accepted by arachne-pnr):
```
set_io led[0]     B5 # D9
```

**Comment by cliffordwolf** [comment]
Fixed in commit 49e3ad4. (It would have been helpful to know that this is a problem with the .pcf parser in icetime, not e.g. the one in icebox_vlog.. ;)

**Comment by whitequark** [comment]
Oh! I had no idea there were several parsers even in icestorm alone. And thanks!

**Comment by cliffordwolf** [comment]
Yeah. I totally forgot about the one in `icetime` and was trying to reproduce the problem with `icebox_vlog` for like 10 minutes before I remembered that there is another .pcf parser in `icetime`.. ;)
