### ISSUE TITLE
wiki

### ISSUE THREAD

**Issue by peepo** [cliffordwolf/icestorm#52]
clifford, would [the icestorm wiki](https://github.com/cliffordwolf/icestorm/wiki) be the place to link to tutorials (like mine ~:")

**Comment by cliffordwolf** [comment]
No.

Quoting the "Links" section of  http://www.clifford.at/icestorm/:

> Links to related projects. Contact me at clifford@clifford.at if you have an interesting and relevant link.

Instead of sending a mail you can also post here of course.
