### ISSUE TITLE
icepll can produce out-of-range DIVF values

### ISSUE THREAD

**Issue by mcflan** [cliffordwolf/icestorm#61]
Hi

I just tried running icepll like this:

`icepll -i 12 -o 200`

to get a 200MHz (ish) output from a 12MHz xtal on the icestick

and got the following output:

```
F_PLLIN:    12.000 MHz (given)
F_PLLOUT:  200.000 MHz (requested)
F_PLLOUT:  201.000 MHz (achieved)

FEEDBACK: SIMPLE
F_PFD:   12.000 MHz
F_VCO:  804.000 MHz

DIVR:  0 (4'b0000)
DIVF: 66 (7'b1000010)
DIVQ:  2 (3'b010)

FILTER_RANGE: 1 (3'b001)

```

The value of 66 for DIVF is out of range (data sheets say 0..63) - I tried it on the Icestick (to check I am not going mad) and indeed it produces the equivalent of it wrapping around to 2, as expected.

I think the issue is at line 101 in the code:

`for (int divf = 0; divf <= 127; divf++)`

Which should probably be:

`for (int divf = 0; divf <= 63; divf++)`

Unless, of course, I am misunderstanding something (I am new to lattice ICE parts and icestorm).

PS: Thanks for all your work on this. It's a completely awesome project and a fantastic achievement.  I am really enjoying working with open source tools on an FPGA. Is there any way to help with / donate to the project?

James.

**Comment by cliffordwolf** [comment]
Thanks for reporting this. Fixed in commit 7d8337a.

The crazy thing is that DIVF really is a 7 bit value. It just looks like the hardware is ignoring the MSB bit.

> Is there any way to help with / donate to the project?

Good bug reports certainly help a lot.  
You can donate here: http://www.clifford.at/yosys/donate.html
