### ISSUE TITLE
Use chipdb*.bin files

### ISSUE THREAD

**Issue by Jesus89** [cliffordwolf/icestorm#71]
Hi, Is there a plan to unify the chipdb binary files between Icestorm and Arachne-pnr?

Now there is a *share/icebox* directory with the chipdbs*.txt (about ~44Mb) and other *share/arachne-pnr* directory with the same information chipdb*.bin (about ~12Mb) for the same toolchain.

Do you plan to generate those chipdb*.bin from the *icebox* tools and read those chipdb*.bin files in the *icetime* tool?

Thanks!

**Comment by cliffordwolf** [comment]
> Do you plan to generate those chipdb*.bin from the icebox tools and read those chipdb*.bin files in the icetime tool?

No. and No.

Creating `chipdb*.bin` from icebox is almost impossible as icebox is written in python and the chipdb.bin files are created/read using the standard c++ serializer/deserializers (see `ChipDB::bread()` and `ChipDB::bwrite()` in arachne-pnr).

For the same same reason it is virtually impossible to read those `chipdb*.bin` files without copying (and keeping in sync) large amounts of code between icetime and arachne-pnr.
