### ISSUE TITLE
icebox_vlog

### ISSUE THREAD

**Issue by cseed** [cliffordwolf/icestorm#8]
I'm getting the following error:
```
Traceback (most recent call last):
  File "/usr/local/bin/icebox_vlog", line 344, in <module>
    for s in sorted(net_segs):
TypeError: unorderable types: str() < tuple()
```

The offending input is here: https://gist.github.com/cseed/7c648bd527f00fd40be1.  Just run `icebox_vlog carry_route_fail1.txt`.

**Comment by cliffordwolf** [comment]
Fixed in commit 19be8895a51a50937261528035c95d4686228528.
