### ISSUE TITLE
err.h is not available on mingw

### ISSUE THREAD

**Issue by rqou** [cliffordwolf/icestorm#85]
The commit dbdc65b65b6862af3b7afdb4ef6c3d2a153541e5 seems to be an attempt to improve some error reporting. However, it uses functions from `err.h` which "are nonstandard BSD extensions" according to [this](http://man7.org/linux/man-pages/man3/err.3.html) man page. This breaks the build for Windows/MinGW-w64.

**Comment by cliffordwolf** [comment]
yeah, that's horrible. I did not realize that when applying the patch. Do you want to prepare a PR that gets rid or `<err.h>` and replaces calls to `errx()` and `warnx()` with something more portable?
